# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: blockialabs
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: api

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    NODE_ENV: ${env:NODE_ENV, 'development'} # Auto detect environment
    NMKR_API_KEY: ${env:NMKR_API_KEY, 'key-local-dev'} # Default for local
    NMKR_BASE_URL: ${env:NMKR_BASE_URL, 'https://studio-api.preprod.nmkr.io'} # NMKR staging URL
    NMKR_CUSTOMER_ID: ${env:NMKR_CUSTOMER_ID} # NMKR Customer Id
    NMKR_PROJECT_UID: ${env:NMKR_PROJECT_UID} # NMKR Project id
    RECEIVER_ADDRESS: ${env:RECEIVER_ADDRESS} # Blockchain
    BLOCKCHAIN: ${env:BLOCKCHAIN, 'Cardano'} # Blockchain
    BATCH_SIZE: ${env:BATCH_SIZE, '500'} # Safe default batch size

plugins:
  - serverless-offline

functions:
  api:
    handler: .build/handler.handler
    events:
      - httpApi: '*'
