# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: blockialabs
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: api

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 300 # Add this line - global default timeout (5 minutes)
  memorySize: 1024 # Add this line - increase memory allocation
  environment:
    NODE_ENV: ${env:NODE_ENV, 'development'} # Auto detect environment
    NMKR_API_KEY: ${env:NMKR_API_KEY, 'key-local-dev'} # Default for local
    NMKR_BASE_URL: ${env:NMKR_BASE_URL, 'https://studio-api.preprod.nmkr.io'} # NMKR staging URL
    NMKR_CUSTOMER_ID: ${env:NMKR_CUSTOMER_ID} # NMKR Customer Id
    NMKR_PROJECT_UID: ${env:NMKR_PROJECT_UID} # NMKR Project id
    NMKR_POLICY_ID: ${env:NMKR_POLICY_ID} # NMKR Policy id
    RECEIVER_ADDRESS: ${env:RECEIVER_ADDRESS} # Wallet address
    BLOCKCHAIN: ${env:BLOCKCHAIN, 'Cardano'} # Blockchain
    MINT_BATCH_SIZE: ${env:MINT_BATCH_SIZE, 10} # Safe default batch size
    MINT_TOTAL_COUNT: ${env:MINT_TOTAL_COUNT, 500} # Safe default batch total
    CONCURRENCY_LIMIT: ${env:CONCURRENCY_LIMIT, 5}
    RETRY_COUNT: ${env:RETRY_COUNT, 3}
    AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}
    AWS_DYNAMO_TABLE_BATCH_RECORDS: ${env:AWS_DYNAMO_TABLE_BATCH_RECORDS, 'BatchRecords'}
    AWS_DYNAMO_TABLE_RECORDS_STATUS: ${env:AWS_DYNAMO_TABLE_RECORDS_STATUS, 'ReportStatus'}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    AWS_REGION: ${env:AWS_REGION, 'us-east-1'} # Default AWS region
    BUCKET_NAME: ${env:BUCKET_NAME, ''} # Default bucket name

plugins:
  - serverless-offline

functions:
  api:
    handler: .build/handler.handler
    events:
      - httpApi: '*'
