name: Deploy Client

on: 
  push:
    branches:
      - main
    paths:
      - 'client/**'

env:
  VITE_API_URL: ${{ secrets.VITE_API_URL }}
  VITE_MINT_PRICE: ${{ secrets.VITE_MINT_PRICE }}
  VITE_MINT_COUNT: ${{ secrets.VITE_MINT_COUNT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./client


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
  
      - name: Build client
        run: npm run build
        working-directory: ./client

      - name: Deploy to S3
        run: |
          aws s3 sync ./client/dist s3://${{ secrets.AWS_FRONTEND_BUCKET }} --delete --cache-control no-cache
      
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"